categories = ["Added", "Changed", "Fixed", "Improved", "Removed"]
colored_output = true
enable_debug = true
enable_footers = false
excluded_commit_tags = []
show_commit_hash = true
show_prefix = false
sort_by = "name"
template_prefix = "JIRA-1234"
default_template = "template.toml"
